[project]
name = "image-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "boto3>=1.42.48,<1.43.0",
    "flask>=3.1.2,<3.2.0",
    "mangum>=0.21.0,<0.21.1",
    "pydantic>=2.12.5,<2.13.0",
    "pydantic-settings>=2.12.0,<2.13.0",
    "python-ulid>=3.1.0,<3.2.0",
]

[dependency-groups]
dev = [
    "boto3-stubs[essential]>=1.42.49,<1.43.0",
    "ipython>=9.10.0,<9.11.0",
    "moto[dynamodb,s3]>=5.1.21,<5.2.0",
    "pytest>=9.0.2,<9.1.0",
    "pytest-cov>=7.0.0,<7.1.0",
    "ruff>=0.15.1,<0.15.2",
]

[tool.uv]
add-bounds = "minor"
